"""
spatial_memory.py
Model 2: Spatial Memory  (Vector-HaSH paper, Fig. 1d)

Grid states are no longer arbitrary: they are generated by path
integration from a known anchor via a sequence of velocities. Sensory
landmarks observed while exploring are bound to the corresponding
hippocampal states (Whs / Wsh) exactly as in item memory, but the *keys*
(grid/hippocampal codewords) are now spatially structured by T(g, v).

Inference supports the "dark" condition: starting from a known anchor
grid state, integrate a velocity sequence with NO sensory input at all,
and predict the sensory landmark expected at each visited location.
"""
import numpy as np
from typing import List
from grid_utils import GridCode, ModuleIndices, Velocity
from scaffold import GridHPCScaffold
from learning_rules import HeteroAssociativeMemory


class SpatialMemory:
    def __init__(self, grid_code: GridCode, scaffold: GridHPCScaffold, Ns: int, rule: str = "pinv"):
        self.grid_code = grid_code
        self.scaffold = scaffold
        self.Ns = Ns
        self.Whs = HeteroAssociativeMemory(Ns, scaffold.Nh, rule=rule)
        self.Wsh = HeteroAssociativeMemory(scaffold.Nh, Ns, rule=rule)

    # ---------------- Learning phase ----------------
    def learn(self, start_indices: ModuleIndices, velocities: List[Velocity],
              sensory_along_path: List[np.ndarray]):
        """Explore a path (start + velocity sequence) and bind whatever
        sensory landmark is observed at each visited location."""
        grid_path = self.grid_code.path_integrate(start_indices, velocities)
        assert len(grid_path) == len(sensory_along_path)
        hpc_path = [self.scaffold.grid_to_hpc(g) for g in grid_path]
        self.Whs.fit(sensory_along_path, hpc_path)
        self.Wsh.fit(hpc_path, sensory_along_path)
        return grid_path, hpc_path

    # ---------------- Learning phase: multiple rooms (Fig 4e/4g) ----------------
    def learn_rooms(self, rooms: List[dict]):
        """Fig 4-style multi-room learning. Each room gets its own initial
        grid state (per the guideline's "simplified implementation may
        assign a different initial grid state to each room"), so a room is
        just another region of the SAME shared grid-hippocampal scaffold.
        All rooms' (sensory, hpc) bindings are pooled into ONE joint
        Whs/Wsh fit -- this is what lets memories from earlier rooms
        remain available after later rooms are learned, as long as the
        pooled key set stays within the scaffold's hetero-associative
        capacity.

        rooms: list of dicts, each with keys
            "start_indices": ModuleIndices,
            "velocities": List[Velocity],
            "landmarks": List[np.ndarray]   (len = len(velocities) + 1)

        Returns per-room (grid_path, hpc_path) lists, in the same order
        as `rooms`, so callers can test recall into any specific room.
        """
        all_sensory: List[np.ndarray] = []
        all_hpc: List[np.ndarray] = []
        per_room_paths = []

        for room in rooms:
            grid_path = self.grid_code.path_integrate(room["start_indices"], room["velocities"])
            landmarks = room["landmarks"]
            assert len(grid_path) == len(landmarks)
            hpc_path = [self.scaffold.grid_to_hpc(g) for g in grid_path]

            all_sensory.extend(landmarks)
            all_hpc.extend(hpc_path)
            per_room_paths.append((grid_path, hpc_path))

        self.Whs.fit(all_sensory, all_hpc)
        self.Wsh.fit(all_hpc, all_sensory)
        return per_room_paths

    # ---------------- Inference phase: dark path integration ----------------
    def recall_along_novel_path(self, start_indices: ModuleIndices,
                                 velocities: List[Velocity], n_cleanup_iter: int = 1, recorder=None):
        """No sensory input is used here at all -- pure velocity-driven
        path integration ("eyes closed"), with scaffold cleanup at every
        step, followed by sensory landmark prediction via Wsh."""
        g = self.grid_code.encode_state(start_indices)
        h = self.scaffold.grid_to_hpc(g)
        predicted_sensory = [self.Wsh.recall(h)]
        if recorder is not None:
            recorder.record(grid_states={"g": g}, node_states={"h": h},
                             weights={"Whs": self.Whs.W, "Wsh": self.Wsh.W}, label="t=0")
        for t, v in enumerate(velocities, start=1):
            g = self.grid_code.shift(g, v)                             # T(g, v)
            h = self.scaffold.grid_to_hpc(g)
            h, g = self.scaffold.cleanup(h, n_iter=n_cleanup_iter)
            predicted_sensory.append(self.Wsh.recall(h))
            if recorder is not None:
                recorder.record(grid_states={"g": g}, node_states={"h": h},
                                 weights={"Whs": self.Whs.W, "Wsh": self.Wsh.W}, label=f"t={t}")
        return predicted_sensory
